---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rfc86

<!-- badges: start -->
<!-- badges: end -->

The goal of rfc86 is to add some benchmarks for reading files via the [proposed GDAL columnar API](https://github.com/rouault/gdal/blob/rfc_86/doc/source/development/rfc/rfc86_column_oriented_api.rst).

## Installation

You can install the development version of rfc86 from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("paleolimbot/rfc86")
```

To use it you will have to build GDAL from source against the [prototype implementation](https://github.com/rouault/gdal/tree/arrow_batch_new).

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(rfc86)
library(geoarrow)
library(sf)
library(vapour)

if (!file.exists("nshn_water_line.parquet")) {
  curl::curl_download(
    "https://github.com/paleolimbot/geoarrow-data/releases/download/v0.0.1/nshn_water_line.parquet",
    "nshn_water_line.parquet"
  )
  
  curl::curl_download(
    "https://github.com/paleolimbot/geoarrow-data/releases/download/v0.0.1/nshn_water_line.gpkg",
    "nshn_water_line.gpkg"
  )
  
  system("ogr2ogr nshn_water_line.fgb nshn_water_line.gpkg")
}

system.time(read_ogr_table("nshn_water_line.gpkg"))
system.time(read_ogr_table("nshn_water_line.fgb"))
system.time(read_ogr_sf("nshn_water_line.gpkg"))
system.time(read_sf("nshn_water_line.gpkg"))
system.time({
  vapour_read_attributes("nshn_water_line.gpkg")
  vapour_read_geometry("nshn_water_line.gpkg")
})
system.time(arrow::read_parquet("nshn_water_line.parquet"))
```
