// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// ogr.cpp
void cpp_init_gdal();
extern "C" SEXP _rfc86_cpp_init_gdal() {
  BEGIN_CPP11
    cpp_init_gdal();
    return R_NilValue;
  END_CPP11
}
// ogr.cpp
list cpp_read_ogr_stream(std::string dsn, sexp stream_xptr);
extern "C" SEXP _rfc86_cpp_read_ogr_stream(SEXP dsn, SEXP stream_xptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_read_ogr_stream(cpp11::as_cpp<cpp11::decay_t<std::string>>(dsn), cpp11::as_cpp<cpp11::decay_t<sexp>>(stream_xptr)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_rfc86_cpp_init_gdal",       (DL_FUNC) &_rfc86_cpp_init_gdal,       0},
    {"_rfc86_cpp_read_ogr_stream", (DL_FUNC) &_rfc86_cpp_read_ogr_stream, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_rfc86(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
