# Generated by cpp11: do not edit by hand

cpp_init_gdal <- function() {
  invisible(.Call(`_rfc86_cpp_init_gdal`))
}

cpp_read_ogr_stream <- function(dsn, stream_xptr) {
  .Call(`_rfc86_cpp_read_ogr_stream`, dsn, stream_xptr)
}
